### ISSUE TITLE
Getting error: could not find `Cargo.toml` in `/code` or any parent directory

### ISSUE THREAD

**Issue by jayraviteja** [StakeSquid/graphprotocol-mainnet-docker#1]
Hello,

I'm a newbie to this environment and technology. Pls help on the below issue.

When I am trying to follow this setup procedure, I've encountered some set of issues..

Resolving one by one, And currently I'm blocked at this error.. 

When I am running **./runagora --help (or) ./runqlog --help** below is the error output.

**error: could not find `Cargo.toml` in `/code` or any parent directory**
**./runagora: line 10: /home/ubuntu/graphprotocol-mainnet-docker/agora/target/release/agora: No such file or directory**

Is Cargo.toml missing?? How do we get it? It seems some manifest file.

**Note:-** Pls check the 7th line in runagora file, Check if **bash -c '(cd /code/agora; cargo build --release)'** need to be changed to  **bash -c '(cd /code; cargo build --release)'**

**Comment by trader-payne** [comment]
You can skip installing both Agora and Qlog for now. They're not mandatory.

**Comment by jayraviteja** [comment]
Unfortunately none of these commands are working either.. 
![image](https://user-images.githubusercontent.com/38829329/110109710-d3ce0d80-7dd3-11eb-9e8b-a6d38de7b3f1.png)

**Comment by trader-payne** [comment]
`Extract queries since` depends on qlog

As for the rest, you're supposed to use an actual IPFS Hash not that placeholder.
The reason why your CLI doesn't connect to the agent is probably because either:
- agent is crash looping
- firewall is blocking the cli
