### ISSUE TITLE
indexer-service:v0.19.2 not starting

### ISSUE THREAD

**Issue by justincavery** [StakeSquid/graphprotocol-mainnet-docker#16]
While this has already been reported through the discord I thought I'd capture it here as well.

When deploying the latest version of the `graphprotocol-mainnet-docker` the `indexer-agent` and `indexer-service` continued to restart.

To fix this I changed the `image: ghcr.io/graphprotocol/indexer-service:v0.19.2` to be `image: ghcr.io/graphprotocol/indexer-service:v0.19.1` which came up fine.

**Comment by trader-payne** [comment]
Thanks! I reverted back to 19.1, I was hoping Ford would release an update to 19.3 to fix the issues, but I haven't seen that yet.
